// GENERATED FILE — do not edit by hand.
// Run `npm run data:outlets` to regenerate from the source datasets.
//
// quality:      0-100, from Lin et al. (2023) PNAS Nexus `pc1` — the first
//               principal component across six expert rating sets. Higher =
//               stronger assessed journalistic standards.
// partisanship: -100 to +100, from Yang et al. (2025) Scientific Data
//               DomainDemo `leaning_score`. Negative = shared mainly by
//               registered Democrats, positive = by registered Republicans.
//               This measures a US sharing audience, NOT editorial stance.

export interface GeneratedOutlet {
  name: string;
  hosts: string[];
  headquarters: string;
  country: string;
  ownership: string;
  funding: string;
  founded: string;
  medium: string;
  quality: number | null;
  partisanship: number | null;
  icon: string | null;
  note?: string;
  reference?: boolean;
}

export interface OutletDataSource {
  key: "quality" | "partisanship";
  label: string;
  citation: string;
  url: string;
}

export const OUTLET_DATA_SOURCES: OutletDataSource[] = [
  {
    key: "quality",
    label: "Journalistic quality",
    citation:
      "Lin, H., Lasser, J., Lewandowsky, S., Cole, R., Gully, A., Rand, D. G., & Pennycook, G. (2023). High level of correspondence across different news domain quality rating sets. PNAS Nexus, 2(9), pgad286.",
    url: "https://doi.org/10.1093/pnasnexus/pgad286"
  },
  {
    key: "partisanship",
    label: "US audience partisanship",
    citation:
      "Yang, K.-C., Goel, P., Quintana-Mathé, A., Horgan, L., McCabe, S. D., Grinberg, N., Joseph, K., & Lazer, D. (2025). DomainDemo: a dataset of domain-sharing activities among different demographic groups on Twitter. Scientific Data, 12(1), 1251.",
    url: "https://doi.org/10.1038/s41597-025-05604-6"
  }
];

export const OUTLET_DATA_GENERATED_AT = "2026-07-21";

export const GENERATED_OUTLETS: GeneratedOutlet[] = [
  { name: "Reuters", hosts: ["reuters.com"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Thomson Reuters (public company)", funding: "Subscriptions and media licensing", founded: "1851", medium: "Wire service", quality: 100, partisanship: -22.4, icon: "icons/outlets/reuters-com.ico", reference: true },
  { name: "Associated Press", hosts: ["apnews.com","ap.org"], headquarters: "New York City, United States", country: "United States", ownership: "Nonprofit cooperative of member newsrooms", funding: "Member fees and content licensing", founded: "1846", medium: "Wire service", quality: 99.8, partisanship: -21, icon: "icons/outlets/apnews-com.png", reference: true },
  { name: "Agence France-Presse", hosts: ["afp.com"], headquarters: "Paris, France", country: "France", ownership: "Autonomous public corporation", funding: "Media licensing and French state subscriptions", founded: "1835", medium: "Wire service", quality: 95.5, partisanship: -33, icon: null },
  { name: "BBC News", hosts: ["bbc.com","bbc.co.uk"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Public corporation (BBC)", funding: "UK licence fee and commercial arms", founded: "1922", medium: "Public broadcaster", quality: 88.2, partisanship: -26.4, icon: "icons/outlets/bbc-com.png", reference: true },
  { name: "NPR", hosts: ["npr.org"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Nonprofit media organization", funding: "Member-station fees, sponsorship, and grants", founded: "1970", medium: "Public radio", quality: 93.1, partisanship: -32.8, icon: "icons/outlets/npr-org.png", reference: true },
  { name: "PBS NewsHour", hosts: ["pbs.org"], headquarters: "Arlington, Virginia, United States", country: "United States", ownership: "Public broadcaster (WETA/PBS)", funding: "Viewer donations, grants, and corporate sponsorship", founded: "1975", medium: "Public TV", quality: 87.4, partisanship: -39, icon: null },
  { name: "The New York Times", hosts: ["nytimes.com"], headquarters: "New York City, United States", country: "United States", ownership: "The New York Times Company (public, Sulzberger family control)", funding: "Subscriptions and advertising", founded: "1851", medium: "Newspaper", quality: 85.9, partisanship: -21.7, icon: "icons/outlets/nytimes-com.png", reference: true },
  { name: "The Washington Post", hosts: ["washingtonpost.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Nash Holdings (Jeff Bezos)", funding: "Subscriptions and advertising", founded: "1877", medium: "Newspaper", quality: 81.9, partisanship: -24.1, icon: "icons/outlets/washingtonpost-com.svg", reference: true },
  { name: "The Wall Street Journal", hosts: ["wsj.com"], headquarters: "New York City, United States", country: "United States", ownership: "News Corp (Murdoch family control)", funding: "Subscriptions and advertising", founded: "1889", medium: "Newspaper", quality: 80.4, partisanship: -13, icon: "icons/outlets/wsj-com.ico", note: "News reporting rates near center; the opinion section is assessed as distinctly right-leaning.", reference: true },
  { name: "The Guardian", hosts: ["theguardian.com"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Guardian Media Group (Scott Trust)", funding: "Reader contributions, subscriptions, and advertising", founded: "1821", medium: "Newspaper", quality: 75, partisanship: -32.1, icon: "icons/outlets/theguardian-com.svg", reference: true },
  { name: "Financial Times", hosts: ["ft.com"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Nikkei Inc.", funding: "Subscriptions and advertising", founded: "1888", medium: "Newspaper", quality: 93, partisanship: -30.9, icon: null },
  { name: "The Economist", hosts: ["economist.com"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "The Economist Group (private)", funding: "Subscriptions and advertising", founded: "1843", medium: "Magazine", quality: 92.6, partisanship: -32.5, icon: "icons/outlets/economist-com.ico", reference: true },
  { name: "Bloomberg", hosts: ["bloomberg.com"], headquarters: "New York City, United States", country: "United States", ownership: "Bloomberg L.P. (private, Michael Bloomberg)", funding: "Terminal subscriptions, media subscriptions, and advertising", founded: "1990", medium: "Financial news service", quality: 84, partisanship: -20, icon: null },
  { name: "Axios", hosts: ["axios.com"], headquarters: "Arlington, Virginia, United States", country: "United States", ownership: "Cox Enterprises", funding: "Advertising, sponsored newsletters, and subscriptions", founded: "2016", medium: "Digital", quality: 89.7, partisanship: -28.9, icon: null },
  { name: "Politico", hosts: ["politico.com","politico.eu"], headquarters: "Arlington, Virginia, United States", country: "United States", ownership: "Axel Springer SE", funding: "Advertising and professional subscriptions", founded: "2007", medium: "Digital and print", quality: 86.3, partisanship: -24.9, icon: null },
  { name: "The Hill", hosts: ["thehill.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Nexstar Media Group", funding: "Advertising", founded: "1994", medium: "Digital and print", quality: 89.9, partisanship: -18.8, icon: null },
  { name: "USA Today", hosts: ["usatoday.com"], headquarters: "McLean, Virginia, United States", country: "United States", ownership: "Gannett (public company)", funding: "Advertising and subscriptions", founded: "1982", medium: "Newspaper", quality: 90.1, partisanship: -6.9, icon: null },
  { name: "ABC News", hosts: ["abcnews.go.com","abcnews.com"], headquarters: "New York City, United States", country: "United States", ownership: "The Walt Disney Company", funding: "Advertising", founded: "1945", medium: "TV network", quality: 86.3, partisanship: -12.9, icon: null },
  { name: "CBS News", hosts: ["cbsnews.com"], headquarters: "New York City, United States", country: "United States", ownership: "Paramount", funding: "Advertising", founded: "1927", medium: "TV network", quality: 88, partisanship: -12.5, icon: null },
  { name: "NBC News", hosts: ["nbcnews.com"], headquarters: "New York City, United States", country: "United States", ownership: "NBCUniversal (Comcast)", funding: "Advertising", founded: "1940", medium: "TV network", quality: 84.4, partisanship: -20, icon: null },
  { name: "CNN", hosts: ["cnn.com"], headquarters: "Atlanta, United States", country: "United States", ownership: "Warner Bros. Discovery", funding: "Advertising and carriage fees", founded: "1980", medium: "Cable news", quality: 65.8, partisanship: -13.2, icon: "icons/outlets/cnn-com.png", reference: true },
  { name: "CNBC", hosts: ["cnbc.com"], headquarters: "Englewood Cliffs, New Jersey, United States", country: "United States", ownership: "NBCUniversal (Comcast)", funding: "Advertising and carriage fees", founded: "1989", medium: "Cable business news", quality: 85, partisanship: -13.1, icon: null },
  { name: "MSNBC", hosts: ["msnbc.com"], headquarters: "New York City, United States", country: "United States", ownership: "Versant (spun off from Comcast in 2025)", funding: "Advertising and carriage fees", founded: "1996", medium: "Cable news", quality: 58.8, partisanship: -41.1, icon: "icons/outlets/msnbc-com.png", reference: true },
  { name: "Fox News", hosts: ["foxnews.com","foxbusiness.com"], headquarters: "New York City, United States", country: "United States", ownership: "Fox Corporation (Murdoch family control)", funding: "Advertising and carriage fees", founded: "1996", medium: "Cable news", quality: 53.4, partisanship: 21.9, icon: "icons/outlets/foxnews-com.png", reference: true },
  { name: "New York Post", hosts: ["nypost.com"], headquarters: "New York City, United States", country: "United States", ownership: "News Corp (Murdoch family control)", funding: "Advertising and subscriptions", founded: "1801", medium: "Tabloid newspaper", quality: 63.9, partisanship: -4.7, icon: "icons/outlets/nypost-com.png", reference: true },
  { name: "The Daily Wire", hosts: ["dailywire.com"], headquarters: "Nashville, Tennessee, United States", country: "United States", ownership: "Private (co-founded by Ben Shapiro and Jeremy Boreing)", funding: "Subscriptions and advertising", founded: "2015", medium: "Digital", quality: 35.7, partisanship: 42.8, icon: "icons/outlets/dailywire-com.png", reference: true },
  { name: "Breitbart News", hosts: ["breitbart.com"], headquarters: "Los Angeles, United States", country: "United States", ownership: "Privately held (Mercer family investment)", funding: "Advertising", founded: "2007", medium: "Digital", quality: 29.7, partisanship: 30.2, icon: "icons/outlets/breitbart-com.svg", reference: true },
  { name: "The Federalist", hosts: ["thefederalist.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Private (FDRLST Media)", funding: "Advertising and donations", founded: "2013", medium: "Digital", quality: 25.7, partisanship: 34.6, icon: null },
  { name: "Newsmax", hosts: ["newsmax.com"], headquarters: "Boca Raton, Florida, United States", country: "United States", ownership: "Newsmax Media (Christopher Ruddy)", funding: "Advertising and subscriptions", founded: "1998", medium: "Cable and digital", quality: 28.7, partisanship: 35.2, icon: "icons/outlets/newsmax-com.ico", reference: true },
  { name: "One America News", hosts: ["oann.com"], headquarters: "San Diego, United States", country: "United States", ownership: "Herring Networks (private)", funding: "Carriage fees and advertising", founded: "2013", medium: "Cable news", quality: 41.5, partisanship: 59.2, icon: null },
  { name: "The Blaze", hosts: ["theblaze.com"], headquarters: "Irving, Texas, United States", country: "United States", ownership: "Blaze Media (private)", funding: "Subscriptions and advertising", founded: "2011", medium: "Digital and streaming", quality: 31.9, partisanship: 49.4, icon: null },
  { name: "Washington Examiner", hosts: ["washingtonexaminer.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Clarity Media Group (Philip Anschutz)", funding: "Advertising and subscriptions", founded: "2005", medium: "Digital and magazine", quality: 50.8, partisanship: 12.8, icon: null },
  { name: "The Washington Times", hosts: ["washingtontimes.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Operations Holdings (Unification Church affiliation)", funding: "Advertising and subsidy", founded: "1982", medium: "Newspaper", quality: 34.5, partisanship: 20, icon: null },
  { name: "National Review", hosts: ["nationalreview.com"], headquarters: "New York City, United States", country: "United States", ownership: "National Review Institute (nonprofit)", funding: "Subscriptions, donations, and advertising", founded: "1955", medium: "Magazine", quality: 57.4, partisanship: 20.4, icon: "icons/outlets/nationalreview-com.ico", reference: true },
  { name: "Reason", hosts: ["reason.com"], headquarters: "Los Angeles, United States", country: "United States", ownership: "Reason Foundation (nonprofit)", funding: "Donations and subscriptions", founded: "1968", medium: "Magazine and digital", quality: 80.5, partisanship: 8.5, icon: null, note: "Libertarian outlook: assessed right-of-center on economics while diverging from conservative positions on social and civil-liberties issues." },
  { name: "The Epoch Times", hosts: ["theepochtimes.com"], headquarters: "New York City, United States", country: "United States", ownership: "Epoch Media Group (associated with the Falun Gong movement)", funding: "Subscriptions, advertising, and donations", founded: "2000", medium: "Newspaper and digital", quality: 26.3, partisanship: 35.3, icon: "icons/outlets/theepochtimes-com.png", reference: true },
  { name: "HuffPost", hosts: ["huffpost.com","huffingtonpost.com"], headquarters: "New York City, United States", country: "United States", ownership: "BuzzFeed, Inc.", funding: "Advertising", founded: "2005", medium: "Digital", quality: 56.8, partisanship: -24.9, icon: null, reference: true },
  { name: "Vox", hosts: ["vox.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Vox Media", funding: "Advertising and reader contributions", founded: "2014", medium: "Digital", quality: 65.4, partisanship: -39.3, icon: "icons/outlets/vox-com.ico", reference: true },
  { name: "Slate", hosts: ["slate.com"], headquarters: "New York City, United States", country: "United States", ownership: "The Slate Group (Graham Holdings)", funding: "Advertising and memberships", founded: "1996", medium: "Digital", quality: 61.3, partisanship: -39.5, icon: null },
  { name: "The Atlantic", hosts: ["theatlantic.com"], headquarters: "Washington, D.C., United States", country: "United States", ownership: "Emerson Collective (majority, Laurene Powell Jobs)", funding: "Subscriptions and advertising", founded: "1857", medium: "Magazine", quality: 80.4, partisanship: -34.3, icon: "icons/outlets/theatlantic-com.png", reference: true },
  { name: "The New Yorker", hosts: ["newyorker.com"], headquarters: "New York City, United States", country: "United States", ownership: "Condé Nast (Advance Publications)", funding: "Subscriptions and advertising", founded: "1925", medium: "Magazine", quality: 66.3, partisanship: -45, icon: null },
  { name: "Time", hosts: ["time.com"], headquarters: "New York City, United States", country: "United States", ownership: "Private (Marc and Lynne Benioff)", funding: "Advertising and subscriptions", founded: "1923", medium: "Magazine", quality: 82.6, partisanship: -23.4, icon: null },
  { name: "Newsweek", hosts: ["newsweek.com"], headquarters: "New York City, United States", country: "United States", ownership: "Newsweek Publishing (private)", funding: "Advertising and subscriptions", founded: "1933", medium: "Digital and magazine", quality: 81.8, partisanship: -25.3, icon: null },
  { name: "Mother Jones", hosts: ["motherjones.com"], headquarters: "San Francisco, United States", country: "United States", ownership: "Foundation for National Progress (nonprofit)", funding: "Reader donations and subscriptions", founded: "1976", medium: "Magazine and digital", quality: 66.1, partisanship: -53.5, icon: "icons/outlets/motherjones-com.png", reference: true },
  { name: "The Nation", hosts: ["thenation.com"], headquarters: "New York City, United States", country: "United States", ownership: "The Nation Company (private)", funding: "Subscriptions and donations", founded: "1865", medium: "Magazine", quality: 66.4, partisanship: -57, icon: null },
  { name: "Jacobin", hosts: ["jacobin.com","jacobinmag.com"], headquarters: "New York City, United States", country: "United States", ownership: "Private (Bhaskar Sunkara)", funding: "Subscriptions and donations", founded: "2010", medium: "Magazine and digital", quality: 60.2, partisanship: -55.9, icon: "icons/outlets/jacobin-com.png", reference: true },
  { name: "Daily Kos", hosts: ["dailykos.com"], headquarters: "Oakland, California, United States", country: "United States", ownership: "Kos Media (private)", funding: "Advertising and donations", founded: "2002", medium: "Digital community blog", quality: 41.4, partisanship: -57.3, icon: null },
  { name: "Salon", hosts: ["salon.com"], headquarters: "New York City, United States", country: "United States", ownership: "Salon Media Group", funding: "Advertising", founded: "1995", medium: "Digital", quality: 53.8, partisanship: -45.9, icon: null },
  { name: "The Intercept", hosts: ["theintercept.com"], headquarters: "New York City, United States", country: "United States", ownership: "First Look Institute (nonprofit, founded with Pierre Omidyar funding)", funding: "Donations", founded: "2014", medium: "Digital", quality: 60.8, partisanship: -41.6, icon: null },
  { name: "ProPublica", hosts: ["propublica.org"], headquarters: "New York City, United States", country: "United States", ownership: "Nonprofit newsroom", funding: "Philanthropic donations", founded: "2007", medium: "Investigative digital newsroom", quality: 85.3, partisanship: -51.4, icon: "icons/outlets/propublica-org.png", reference: true },
  { name: "Business Insider", hosts: ["businessinsider.com"], headquarters: "New York City, United States", country: "United States", ownership: "Axel Springer SE", funding: "Advertising and subscriptions", founded: "2007", medium: "Digital", quality: 80.5, partisanship: -15.8, icon: null },
  { name: "Forbes", hosts: ["forbes.com"], headquarters: "Jersey City, New Jersey, United States", country: "United States", ownership: "Integrated Whale Media (majority)", funding: "Advertising and licensing", founded: "1917", medium: "Magazine and digital", quality: 83, partisanship: -12.6, icon: null, note: "Staff reporting rates higher than the large outside-contributor network publishing under the same brand." },
  { name: "Semafor", hosts: ["semafor.com"], headquarters: "New York City, United States", country: "United States", ownership: "Private (Ben Smith and Justin Smith)", funding: "Advertising and events", founded: "2022", medium: "Digital", quality: null, partisanship: null, icon: null },
  { name: "NewsNation", hosts: ["newsnationnow.com"], headquarters: "Chicago, United States", country: "United States", ownership: "Nexstar Media Group", funding: "Advertising and carriage fees", founded: "2020", medium: "Cable news", quality: 94.7, partisanship: 1.4, icon: null },
  { name: "The Christian Science Monitor", hosts: ["csmonitor.com"], headquarters: "Boston, United States", country: "United States", ownership: "The First Church of Christ, Scientist", funding: "Subscriptions and church endowment", founded: "1908", medium: "Digital and weekly print", quality: 93.5, partisanship: -28.9, icon: null },
  { name: "Al Jazeera", hosts: ["aljazeera.com"], headquarters: "Doha, Qatar", country: "Qatar", ownership: "Al Jazeera Media Network (Qatari state-funded)", funding: "Qatari government funding", founded: "1996", medium: "Broadcaster and digital", quality: 77.9, partisanship: -47.8, icon: null, note: "State-funded: assessments note reliable field reporting alongside limited critical coverage of Qatar and its regional interests." },
  { name: "RT", hosts: ["rt.com"], headquarters: "Moscow, Russia", country: "Russia", ownership: "ANO TV-Novosti (Russian state)", funding: "Russian government funding", founded: "2005", medium: "State broadcaster and digital", quality: 29.3, partisanship: -8.8, icon: null, note: "Assessed as a Russian state propaganda channel; placement on a left-right axis is less meaningful than its pro-Kremlin orientation." },
  { name: "Xinhua", hosts: ["news.cn","xinhuanet.com"], headquarters: "Beijing, China", country: "China", ownership: "Chinese state news agency", funding: "Chinese government funding", founded: "1931", medium: "State wire service", quality: 69.1, partisanship: -11.4, icon: null, note: "Official state agency of the Chinese government; assessments treat its political coverage as state messaging rather than independent journalism." },
  { name: "Deutsche Welle", hosts: ["dw.com"], headquarters: "Bonn, Germany", country: "Germany", ownership: "German public international broadcaster", funding: "German federal tax funding", founded: "1953", medium: "Public broadcaster", quality: 86.4, partisanship: -32, icon: null },
  { name: "France 24", hosts: ["france24.com"], headquarters: "Issy-les-Moulineaux, France", country: "France", ownership: "France Médias Monde (French public)", funding: "French public funding", founded: "2006", medium: "Public broadcaster", quality: 87.9, partisanship: -25.3, icon: null },
  { name: "CBC News", hosts: ["cbc.ca"], headquarters: "Toronto, Canada", country: "Canada", ownership: "Canadian Broadcasting Corporation (public)", funding: "Canadian public funding and advertising", founded: "1936", medium: "Public broadcaster", quality: 81.7, partisanship: -27.5, icon: null },
  { name: "The Globe and Mail", hosts: ["theglobeandmail.com"], headquarters: "Toronto, Canada", country: "Canada", ownership: "The Woodbridge Company", funding: "Subscriptions and advertising", founded: "1844", medium: "Newspaper", quality: 81.6, partisanship: -31.3, icon: null },
  { name: "The Telegraph", hosts: ["telegraph.co.uk"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Telegraph Media Group", funding: "Subscriptions and advertising", founded: "1855", medium: "Newspaper", quality: 61.2, partisanship: -16.1, icon: null },
  { name: "Daily Mail", hosts: ["dailymail.co.uk"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "DMGT (Rothermere family control)", funding: "Advertising", founded: "1896", medium: "Tabloid newspaper", quality: 38.4, partisanship: -5.2, icon: null },
  { name: "The Sun", hosts: ["thesun.co.uk"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "News UK (News Corp)", funding: "Advertising", founded: "1964", medium: "Tabloid newspaper", quality: 56.8, partisanship: -1, icon: null },
  { name: "The Independent", hosts: ["independent.co.uk","the-independent.com"], headquarters: "London, United Kingdom", country: "United Kingdom", ownership: "Independent Digital News & Media (Lebedev holding)", funding: "Advertising and subscriptions", founded: "1986", medium: "Digital", quality: 73.4, partisanship: -28.8, icon: null },
  { name: "The Hindu", hosts: ["thehindu.com"], headquarters: "Chennai, India", country: "India", ownership: "The Hindu Group (Kasturi & Sons)", funding: "Subscriptions and advertising", founded: "1878", medium: "Newspaper", quality: 70.5, partisanship: -37.1, icon: null },
  { name: "South China Morning Post", hosts: ["scmp.com"], headquarters: "Hong Kong", country: "China (Hong Kong SAR)", ownership: "Alibaba Group", funding: "Subscriptions and advertising", founded: "1903", medium: "Newspaper", quality: 76.8, partisanship: -17.1, icon: null, note: "Assessments note professional reporting with a tilt toward Beijing-friendly framing on mainland-China politics since the Alibaba acquisition." },
  { name: "The Jerusalem Post", hosts: ["jpost.com"], headquarters: "Jerusalem", country: "Israel", ownership: "Jerusalem Post Group (private)", funding: "Advertising and subscriptions", founded: "1932", medium: "Newspaper", quality: 80.5, partisanship: 3.1, icon: null },
  { name: "Haaretz", hosts: ["haaretz.com"], headquarters: "Tel Aviv, Israel", country: "Israel", ownership: "Schocken family and minority investors", funding: "Subscriptions and advertising", founded: "1918", medium: "Newspaper", quality: 67.2, partisanship: -35.7, icon: null },
  { name: "ABC News (Australia)", hosts: ["abc.net.au"], headquarters: "Sydney, Australia", country: "Australia", ownership: "Australian Broadcasting Corporation (public)", funding: "Australian public funding", founded: "1932", medium: "Public broadcaster", quality: 89.3, partisanship: -24.6, icon: null },
  { name: "The Sydney Morning Herald", hosts: ["smh.com.au"], headquarters: "Sydney, Australia", country: "Australia", ownership: "Nine Entertainment", funding: "Subscriptions and advertising", founded: "1831", medium: "Newspaper", quality: 76.6, partisanship: -29, icon: null }
];
